# Autogenerated file.
# Do not edit.
# Do not change location.

message("Setting Ipopt for linux-64")

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)


set(IPOPT_INCLUDE_DIRS "${ROOT_DIR}/include/coin;" CACHE INTERNAL "" FORCE)

set(IPOPT_LIBRARIES "${ROOT_DIR}/lib/libcoinasl.so;" 
		    "${ROOT_DIR}/lib/libcoinblas.so;" 
		    "${ROOT_DIR}/lib/libcoinlapack.so;"
 		    "${ROOT_DIR}/lib/libcoinmumps.so;"
 		    "${ROOT_DIR}/lib/libipopt.so;"
 		    "${ROOT_DIR}/lib/libcoinmetis.so;"
		     CACHE INTERNAL "" FORCE)

set(IPOPT_TARGET "IPOPT" CACHE INTERNAL "" FORCE)

set(IPOPT_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(IPOPT_DEPENDS "" CACHE INTERNAL "" FORCE)
 
