# Autogenerated file.
# Do not edit.
# Do not change location.

message("Setting OpenHRC for linux-64")

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)


set(OpenHRC_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE INTERNAL "" FORCE)
set(OpenHRC_LIBRARIES "${ROOT_DIR}/lib/linux-64/libopenhrc.a;" CACHE INTERNAL "" FORCE)

set(OpenHRC_TARGET "OpenHRC" CACHE INTERNAL "" FORCE)

set(OpenHRC_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(OpenHRC_DEPENDS "" CACHE INTERNAL "" FORCE)
 
